FROM python:3.11

WORKDIR /app

COPY . /app

RUN mkdir -p /root/.aws
COPY .aws/credentials /root/.aws/
COPY .aws/config /root/.aws/

RUN pip install -r requirements.txt

EXPOSE 5000

CMD ["python", "app.py"]
