FROM python:3.11

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . /app

RUN mkdir -p /root/.aws
COPY .aws/credentials /root/.aws/
COPY .aws/config /root/.aws/

EXPOSE 5000

CMD ["python", "app.py"]
